/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cantBeEvilSol from "./CantBeEvil.sol";
export type { cantBeEvilSol };
export type { Lock } from "./Lock";
