/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICantBeEvil,
  ICantBeEvilInterface,
} from "../../../../@a16z/contracts/licenses/ICantBeEvil";

const _abi = [
  {
    inputs: [],
    name: "getLicenseName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLicenseURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICantBeEvil__factory {
  static readonly abi = _abi;
  static createInterface(): ICantBeEvilInterface {
    return new utils.Interface(_abi) as ICantBeEvilInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICantBeEvil {
    return new Contract(address, _abi, signerOrProvider) as ICantBeEvil;
  }
}
