/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CantBeEvil__factory } from "./CantBeEvil__factory";
export { ICantBeEvil__factory } from "./ICantBeEvil__factory";
