"service": "${self:custom.config.name}"
"useDotenv": true
"provider":
  "name": "aws"
  "runtime": "nodejs16.x"
  "memorySize": 1024
  "timeout": 10
  "iam":
    "role":
      "statements":
        - "Effect": "Allow"
          "Action": "*"
          "Resource": "arn:aws:qldb:*:*:*"
        - "Effect": "Allow"
          "Action":
            - "lambda:InvokeFunction"
          "Resource": "*"
  "environment":
    "stackName": "${self:custom.config.name}-${opt:stage, self:provider.stage, 'dev'}"
    "BASE_URL":
      "Fn::Join":
        - ""
        - - " https://"
          - "Ref": "ApiGatewayRestApi"
          - ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.sta\
            ge}/"
    "HOME": "/tmp"
  "layers":
    - "arn:aws:lambda:us-east-1:210049126456:layer:hardhat-lambda-layer:3"
"plugins":
  - "serverless-webpack"
  - "serverless-api-gateway-throttling"
  - "serverless-plugin-info-json"
  - "serverless-plugin-warmup"
  - "serverless-prune-plugin"
  - "serverless-dotenv-plugin"
"resources":
  "Description": "Interface for Hellosign gmSign API"
"custom":
  "config": "${file(./config.json)}"
  "apiGatewayThrottling":
    "maxRequestsPerSecond": 100
    "maxConcurrentRequests": 50
  "warmup":
    "prewarm": true
  "prune":
    "automatic": true
    "number": 1
  "webpack":
    "includeModules": false
  "stage": "${opt:stage, \"dev\"}"
  "region": "${opt:region, self:provider.region, \"us-east-2\"}"
  "QLDB":
    "deleteProtectionEnabled":
      "dev": false
      "prod": true
      "other": false
"functions":
  "deployNFTContract":
    "handler": "handlers.deployNFTContract"
    "timeout": 30
    "events":
      - "http":
          "path": "/make-nft-contract"
          "method": "post"
          "cors": true
          "private": false
  "doDeploy":
    "handler": "handlers.doDeploy"
    "timeout": 300
  "mintNFT":
    "handler": "handlers.mintNFT"
    "timeout": 300
    "events":
      - "http":
          "path": "/mintNFT"
          "method": "post"
          "cors": true
          "private": false
  "getUCANToken":
    "handler": "handlers.getUCANToken"
    "timeout": 30
    "events":
      - "http":
          "path": "/ucan-token"
          "method": "get"
          "cors": true
          "private": false
  "getContracts":
    "handler": "handlers.getContracts"
    "timeout": 30
    "events":
      - "http":
          "path": "/contracts"
          "method": "get"
          "cors": true
          "private": false
  "updateContract":
    "handler": "handlers.updateContract"
    "timeout": 30
    "events":
      - "http":
          "path": "/contracts"
          "method": "post"
          "cors": true
          "private": false
  "addContract":
    "handler": "handlers.addContract"
    "timeout": 30
    "events":
      - "http":
          "path": "/contracts/add"
          "method": "post"
          "cors": true
          "private": false
  "removeContract":
    "handler": "handlers.removeContract"
    "timeout": 30
    "events":
      - "http":
          "path": "/contracts"
          "method": "delete"
          "cors": true
          "private": false
